public class practice2 {

    //method 1
    public void multipleParameters(integer kk, String rr, Boolean mm) {

        kk= kk+100;
        Integer myAge=kk;
        System.debug('My age is '+ kk);

        rr=rr+' abuziddin';
        String myName=rr;
        System.debug('My name is '+rr);

        Boolean allwaysLove=mm;
        System.debug('Love is always win '+ allwaysLove);        

    }
    //method 2
    public void guzel(string a1, integer b1, Boolean c1){

        b1= b1 + 5000;
        String myHomeTown=a1;
        System.debug('My home town is '+myHomeTown);
        integer myExperience=b1;
        System.debug('Total my experience is '+myExperience);
        Boolean Allah1=c1;
        System.debug('Allah birdir ve tektir '+true);

    }

    public void harbiyeli(Boolean ee, string tt, integer ff){
        
        tt=tt+'Kayacan';
        string myDadName=tt;
        System.debug('My dads name is '+ tt);
        Boolean haveClassToday=ee;
        System.debug('Do we have class today? '+ee);

        ff=ff+1;
        Integer myfootSize=ff;
        System.debug('My foot size is '+ff);
        

    }
}
