public class Practice1 {
    public void Practice1() {

        String myName='Suheyb';
        String myLastName='Kayacan';
        Integer myAge=38;
        Boolean imRich=false;
        String myFullN= myName+myLastName;

        System.debug(myName);
        System.debug(myAge);
        System.debug(imRich);
        System.debug(myfullN);
    }

    public void method1(string st){
        string mySchoolName=st;
        System.debug('My school Name is '+ mySchoolName);

    }

    public void unuttum(String r){

        String myHomeName= ' maison du comte';
        System.debug('My home name is '+ myHomeName)
    }

    public void myCatAge1(Integer ww){

        Integer myCatAge=ww;
        System.debug('My cat age is '+ myCatAge);

        Integer myAge=ss;
        System.debug('my early age'+ss);
    }

    public void sonDeneme(Boolean oo){

        Boolean happyLife=oo;
        System.debug('I m learning sales force insallah  '+happyLife);

    }

}
