public class Practice3Parameters {
    public void Palatine(String s1, integer i2, Boolean b1){

        s1=s1+' Red Karisimi bok rengi';
        String myHairColor=s1;
        System.debug('My hair Color is '+ myHairColor);

        i2=i2+5000;
        Integer worldAge=i2;
        System.debug('World age is '+worldAge);

        Boolean haveMoney=b1;
        System.debug('Have money? '+ haveMoney);
    }

    public void Schaumburg(string dd, Integer dd2, Boolean dd3){

        string apartmentName= dd;
        System.debug('apt name was '+dd);
        Integer stayed= dd2;
        System.debug('Stayed '+dd2);
        Boolean liked = dd3;
        System.debug('Like it? '+dd3);

    }
    
}
