public class sabah {
    public void sabah1(String k) {
        string myname=k;
        System.debug(myname);

    }
    public void sabah2(integer u){

        Integer myHeight=u;
        System.debug(myHeight);


    }
    public void sabah3(Boolean r){

        Boolean rich=r;
        System.debug(rich);
    }

    public void ali(string s, integer b, Boolean j){

        string mySchool=s;
        System.debug(mySchool);


        Integer myScore=b;
        System.debug(myScore);

        Boolean haveMoney=True;
        System.debug(haveMoney);

    }

    public void bardak(string w, integer g, Boolean x){

        string haveName=w;
        System.debug(haveName);

        Integer age4=g;
        System.debug(age4);

        Boolean moneytrap=x;
        System.debug(moneytrap);
    }
    
}
