public class Traning1 {
    public void deneme1(){
        String myName= 'Suheyb';
        String myLastName='Kayacan';
        String myFullName=myName + myLastName;
        integer totalFamilyMembers=3;
        integer myAge=38;
        Boolean happyLife=false;
        Boolean imArchitect=true;


        System.debug('my Name is '+ myName);
        System.debug('My full name is '+myFullName);
        System.debug('My age is '+ myAge);
        System.debug('Total Family member is '+totalFamilyMembers);
        System.debug('My occupation is '+ imArchitect);
        System.debug('Im happy with my life '+happyLife);
    }

    public void deneme2(string ab){

        String batchName=ab;
        System.debug('our batch name is '+ batchName);
    }

    public void denemex(string nn){
        string wifeName=nn;
        System.debug('Wifes Name is '+wifeName);
    }

    public void denemey(Integer yy){

        Integer wifeAge=yy;
        System.debug('My Wife age is '+ wifeAge);
    }

    public void deneme3(integer abc){
        integer myAge=abc;
        System.debug(abc);
    }

    public void deneme4(Boolean abcd){
        Boolean happyLife= abcd;
        System.debug(abcd);
    }

    public void denemeson(string uu){

        String sonKez=uu;
        System.debug('Son kez deniyoruz '+ sonKez);
    }
}
   

