Humans love= new Humans();
string k1 =love.FullName('suheyb','kayacan');
System.debug('Full name is ..... '+k1);

String f= love.FullName2('AYSENUR', 'KAYACAN');
System.debug('Wifes Name in Lower Case is.......... '+ f);

string p1= love.Ozel('ceyda', 'KAYACAN');
system.debug('together name .......... ' + p1);

integer age= love.age(date.newInstance(1985, 01, 20));
System.debug(age);

String t=love.okul('varmisin', 'YOKMUSUN');
System.debug(t);
