practice2 love= new practice2();
love.multipleParameters(20, 'suheyb', true);
love.guzel('Isparta', 15, true);

String v1='Dunya';
Integer v2=50;
love.guzel(v1, v2, True);

love.harbiyeli(False, 'Abdullah', 11);

String p3='Monariza';
Integer p2=300;
love.harbiyeli(False, p3, p2);
System.debug(p3+p2);

String ll='Johncim ';
Integer ll2=123;
love.harbiyeli(True, ll, ll2);
System.debug(ll);






























